ERROR - 2024-11-26 22:22:58 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\biblioteca\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\biblioteca\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `prestam...', Array, false)
#4 C:\xampp\htdocs\biblioteca\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\biblioteca\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\biblioteca\app\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\biblioteca\app\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(NULL)
#8 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\biblioteca\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `prestam...', Array, false)
#3 C:\xampp\htdocs\biblioteca\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\biblioteca\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\biblioteca\app\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\biblioteca\app\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(NULL)
#7 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-11-26 22:22:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT `prestamo`.`id_prestamo`, `prestamo`.`fecha_hora`, `prestamo`.`fecha_hora_entrega`, `usuario`.`nombre_usuario`, `libro`.`nombre_libro`
FROM `prestamo`
JOIN `usuario` ON `prestamo`.`id_usuario` = `usuario`.`id_usuario`
JOIN `libro` ON `prestamo`.`id_libro` = `libro`.`id_libro`
WHERE `prestamo`.`id_usuario` IS NULL', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(null)
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:28:48 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT "utf8pre...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\biblioteca\app\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(NULL)
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Home->index()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:28:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT "utf8prestamo"."id_prestamo", "utf8prestamo"."fecha_hora", "utf8prestamo"."fecha_hora_entrega", "utf8usuario"."nombre_usuario", "utf8libro"."nombre_libro"
FROM "utf8prestamo"
JOIN "utf8usuario" ON "utf8prestamo"."id_usuario" = "utf8usuario"."id_usuario"
JOIN "utf8libro" ON "utf8prestamo"."id_libro" = "utf8libro"."id_libro"
WHERE "utf8prestamo"."id_usuario" IS NULL', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(null)
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:28:53 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT "utf8pre...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\biblioteca\app\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(NULL)
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Home->index()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:28:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT "utf8prestamo"."id_prestamo", "utf8prestamo"."fecha_hora", "utf8prestamo"."fecha_hora_entrega", "utf8usuario"."nombre_usuario", "utf8libro"."nombre_libro"
FROM "utf8prestamo"
JOIN "utf8usuario" ON "utf8prestamo"."id_usuario" = "utf8usuario"."id_usuario"
JOIN "utf8libro" ON "utf8prestamo"."id_libro" = "utf8libro"."id_libro"
WHERE "utf8prestamo"."id_usuario" IS NULL', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\PrestamosModel.php(28): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Home.php(26): App\Models\PrestamosModel->obtenerPrestamosPorUsuario(null)
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:34:26 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:34:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:35:02 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:35:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:35:43 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:35:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:35:55 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:35:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-26 22:38:20 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:38:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:39:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-26 22:39:36 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:39:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �biblioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:40:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-26 22:40:05 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �Bibioteca� in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:77
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 77)
#1 C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php(77): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#10 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-26 22:40:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  no existe la base de datos �Bibioteca�
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:40:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-11-26 22:40:21 --> Error connecting to the database: CodeIgniter\Database\Exceptions\DatabaseException: ERROR:  valor no válido para el parámetro «client_encoding»: «utf8mb4» in C:\xampp\htdocs\biblioteca\system\Database\Postgre\Connection.php:97
Stack trace:
#0 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(421): CodeIgniter\Database\Postgre\Connection->connect(false)
#1 C:\xampp\htdocs\biblioteca\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\biblioteca\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#3 C:\xampp\htdocs\biblioteca\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\biblioteca\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\biblioteca\app\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\biblioteca\app\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
#7 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
#8 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\biblioteca\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\biblioteca\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\biblioteca\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\biblioteca\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-11-26 22:40:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [Postgre]: ERROR:  valor no válido para el parámetro «client_encoding»: «utf8mb4»
[Method: POST, Route: login/consultarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "utf8usuario"
WHERE "usuario_login" = :usuario_login:
AND "clave" = :clave:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\LoginModel.php(22): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Login.php(78): App\Models\LoginModel->validarUsuario('ferley', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Login->consultarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:42:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:42:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:42:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:42:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2024-11-26 22:42:40 --> [DEPRECATED] Creation of dynamic property App\Controllers\Usuarios::$validation is deprecated in APPPATH\Controllers\usuarios.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Usuarios->__construct()
 2 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:42:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:42:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:42:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:58:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:58:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:58:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:59:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 22:59:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2024-11-26 22:59:06 --> [DEPRECATED] Creation of dynamic property App\Controllers\Usuarios::$validation is deprecated in APPPATH\Controllers\usuarios.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\Usuarios->__construct()
 2 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-11-26 22:59:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 23:00:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 23:00:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-11-26 23:00:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
